from enum import StrEnum


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    SUCCESS = "PAYMENT_SUCCESS"
    FAILED = "PAYMENT_FAILED"
    REFUND_PENDING = "REFUND_PENDING"
    REFUND_FAILED = "REFUND_FAILED"


class OrderStatus(StrEnum):
    PENDING = "ORDER_PENDING"
    PAID = "ORDER_PAID"
    CANCELLED = "ORDER_CANCELLED"
    UNKNOWN = "ORDER_STATUS_UNKNOWN"


class FailureCategory(StrEnum):
    HIGH_RISK_FRAUD_BLOCK = "HIGH_RISK_FRAUD_BLOCK"
    TEMPORARY_PAYMENT_FAILURE = "TEMPORARY_PAYMENT_FAILURE"
    CUSTOMER_CORRECTABLE = "CUSTOMER_CORRECTABLE"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    EXPIRED_CARD = "EXPIRED_CARD"
    CUSTOMER_CANCELLED_CHECKOUT = "CUSTOMER_CANCELLED_CHECKOUT"


class ProviderHealth(StrEnum):
    HEALTHY = "HEALTHY"
    DOWN = "PROVIDER_DOWN"
    UNKNOWN = "UNKNOWN"


class PaymentFailureSource(StrEnum):
    CUSTOMER = "CUSTOMER"
    PROVIDER = "PROVIDER"
    BANK = "BANK"
    SYSTEM = "SYSTEM"


class PaymentFailureStep(StrEnum):
    AUTHORIZATION = "AUTHORIZATION"
    CAPTURE = "CAPTURE"
    CHECKOUT = "CHECKOUT"
    REFUND = "REFUND"


class RecoveryAction(StrEnum):
    REFUND_RECONCILE = "REFUND_RECONCILE"
    RECONCILE = "RECONCILE"
    BLOCK_RETRY = "BLOCK_RETRY"
    WAIT_AND_NOTIFY = "WAIT_AND_NOTIFY"
    RETRY_NOW = "RETRY_NOW"
    ALTERNATE_PAYMENT = "ALTERNATE_PAYMENT"
    RESUME_PAYMENT = "RESUME_PAYMENT"
    TRACK_REFUND = "TRACK_REFUND"
    ESCALATE = "ESCALATE"
    REVIEW = "REVIEW"


class RecoveryCaseStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"